import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import StoreProvider from "./store/storeProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Muslim Rishta Online",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <StoreProvider>
          <Navbar />
          {children}

          <Footer />
        </StoreProvider>
      </body>
    </html>
  );
}
